### ISSUE TITLE
Cannot configure unknown backend ...

### ISSUE THREAD

**Issue by mxmilkb** [cbdevnet/midimonster#37] opened 2019-12-03 22:08 UTC
```
% midimonster /usr/share/midimonster/osc-artnet.cfg
Cannot configure unknown backend artnet
Failed to read configuration file /usr/share/midimonster/osc-artnet.cfg
MIDIMonster v0.2
Usage:
	midimonster <configfile>
% midimonster /usr/share/midimonster/midi-mouse.cfg
Cannot configure unknown backend midi
Failed to read configuration file /usr/share/midimonster/midi-mouse.cfg
MIDIMonster v0.2
Usage:
	midimonster <configfile>
```

Files the package provides;
```
midimonster-git /usr/
midimonster-git /usr/bin/
midimonster-git /usr/bin/midimonster
midimonster-git /usr/lib/
midimonster-git /usr/lib/midimonster/
midimonster-git /usr/lib/midimonster/artnet.so
midimonster-git /usr/lib/midimonster/evdev.so
midimonster-git /usr/lib/midimonster/jack.so
midimonster-git /usr/lib/midimonster/loopback.so
midimonster-git /usr/lib/midimonster/lua.so
midimonster-git /usr/lib/midimonster/maweb.so
midimonster-git /usr/lib/midimonster/midi.so
midimonster-git /usr/lib/midimonster/osc.so
midimonster-git /usr/lib/midimonster/sacn.so
midimonster-git /usr/share/
midimonster-git /usr/share/midimonster/
midimonster-git /usr/share/midimonster/demo.lua
midimonster-git /usr/share/midimonster/evdev.cfg
midimonster-git /usr/share/midimonster/flying-faders.cfg
midimonster-git /usr/share/midimonster/flying-faders.lua
midimonster-git /usr/share/midimonster/launchctl-sacn.cfg
midimonster-git /usr/share/midimonster/lua.cfg
midimonster-git /usr/share/midimonster/maweb-flying-faders.cfg
midimonster-git /usr/share/midimonster/midi-mouse.cfg
midimonster-git /usr/share/midimonster/midi-osc.cfg
midimonster-git /usr/share/midimonster/osc-artnet.cfg
midimonster-git /usr/share/midimonster/osc-kbd.cfg
midimonster-git /usr/share/midimonster/osc-xy.cfg
midimonster-git /usr/share/midimonster/unifest-17.cfg
```

And the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=midimonster-git) that creates the package.

**Comment by cbdevnet** [comment] 2019-12-03 22:18
Hmm, this looks like the `PLUGINS` variable was not set properly while the main executable was built, normally MIDIMonster outputs "Registered backend <backend-name>" during startup, which is missing here, indicating that no backend is loaded, which also explains the message.

I'll try to reproduce the problem

**Comment by cbdevnet** [comment] 2019-12-03 22:36
Seems like I'll have to spin up an Arch VM for testing, as the saying goes: "It works on my (debian) machine" ;)

**Comment by cbdevnet** [comment] 2019-12-03 23:41
With the help of @keldu we traced it to the build flags makepkg adds to the build environment, I'll update once we have the specific culprit :)

**Comment by cbdevnet** [comment] 2019-12-04 00:14
Fixed by marking the `init` symbols explicitly visible for all backends in 1107a91861189d28d771d02d721d61b403aac38a

**Closed by cbdevnet** 2019-12-04 00:14 UTC

**Comment by cbdevnet** [comment] 2019-12-04 01:39
And thank you @mxmilkb for creating the PKGBUILD! Much appreciated :)
