### ISSUE TITLE
disable mappings in running config

### ISSUE THREAD

**Issue by GralfR** [cbdevnet/midimonster#73] opened 2020-07-27 15:28 UTC
Idea!

It would be helpful, if one could create a config with some kind of groups for the mappings and if those groups could be enabled and disabled while running MidiMonster.
If enabling/disabling mappings could be triggered by external events, this would help in cases like the maweb current fader page.

Example:
I create a config with mapping faderpage 1 to midi-controlchange 1 to 15. This mapping has to be grouped and needs some kind of ID.
Next I create a mapping for faderpage 2 to midi-controlchange 1 to 15, too. This also needs to be grouped and needs some kind of another ID.
Without those IDs faderpage 1 and faderpage 2 would be mapped to the same midi-controllers, which is not useful.

Now the IDs come into focus. There needs to be some kind of selector, which enables and disables those ID. For example:
`[selector]
midi.note0 > ID0
midi.note1 > ID1`

Now I'm able to select/enable all mapping with ID0 by setting note0 to 100% and disable/mute all mapping with ID1 by setting note1 to 0%. This selector needs to work during runtime and should be mapable to all backends.

With external keyboard or by external events (e.g. LUA sending current fader page number from MA2) one can switch between different mappings without reloading the config-file.

I think, this would be a workaround for the MA current-faderpage-problem (because I don't expect there being any API-solution) and even could offer some kind of group/mapping-fader if those IDs are not only boolean on/off but also used as a multiplier 0 to 100%.

I don't know, how much work this needs and how much the core has to be adapted, but would be nice to have the current-faderpage-problem solved.

regards
Gralf

**Comment by cbdevnet** [comment] 2020-07-27 17:50
This is (if I understand it correctly) a duplicate of #42, where layering (allowing channels to select different mappings at runtime) was requested.

I plan on implementing this by making `[map]` section named entities (like `[map map1]`, similar to how instances already work), which can be enabled and disabled by events.

In the meantime, there is a sample configuration which does this via Lua, which admittedly gets complex with more mappings quite quickly, so it's not optimal.

**Closed** 2020-07-27 17:51 UTC
